name: Github CI for Space Repo
on: [ push, pull_request ]
jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - run: echo "The job will running..."
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: cd backend && npm install
      - run: cd backend && npx prisma generate --schema=./src/database/prisma/schema.prisma
      - run: cd backend && npm run build
      - run: cd backend && npm test
      - run: echo "Done."